env:
    global:
        - REPO_DIR=cffi
        - PLAT=aarch64
        - MB_ML_VER=2014
        - DOCKER_TEST_IMAGE=multibuild/xenial_arm64v8

language: generic
services: docker
os: linux

jobs:
  exclude:
      # Exclude the default Python 3.5 build
      - python: 3.5
  include:
      - arch: arm64
        env:
          - MB_PYTHON_VERSION=3.6
      - arch: arm64
        env:
          - MB_PYTHON_VERSION=3.7
      - arch: arm64
        env:
          - MB_PYTHON_VERSION=3.8
      - arch: arm64
        env:
          - MB_PYTHON_VERSION=3.9

before_install:
    - sudo apt-get install mercurial
    - hg clone https://foss.heptapod.net/pypy/cffi
    - (cd cffi; hg up -r `hg tags --template '{tag}\n' | grep '^v' | head -n1`)
    - TEST_DEPENDS="pytest pycparser"
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

after_success:
    - pip install twine
    - twine check ${TRAVIS_BUILD_DIR}/wheelhouse/*
    - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then twine upload ${TRAVIS_BUILD_DIR}/wheelhouse/*; fi
